<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Grace Houghton">

<title>stat408project_Houghton</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="stat408project_Houghton_files/libs/clipboard/clipboard.min.js"></script>
<script src="stat408project_Houghton_files/libs/quarto-html/quarto.js"></script>
<script src="stat408project_Houghton_files/libs/quarto-html/popper.min.js"></script>
<script src="stat408project_Houghton_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="stat408project_Houghton_files/libs/quarto-html/anchor.min.js"></script>
<link href="stat408project_Houghton_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="stat408project_Houghton_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="stat408project_Houghton_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="stat408project_Houghton_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="stat408project_Houghton_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">stat408project_Houghton</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Grace Houghton </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="stat-408-project" class="level2">
<h2 class="anchored" data-anchor-id="stat-408-project">Stat 408 Project</h2>
<p>Step 1 and 2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#read in both data sets</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>batting2021 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Data/batting2021.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>batting2022 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Data/batting2022.csv"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#combine data sets</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>batting2122 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(batting2021, batting2022)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#batting2122</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co">#clean the dataset</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co">#sum(is.na(batting2122))</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">#have one NA value will make NA=0</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>batting2122 <span class="ot">&lt;-</span> <span class="fu">apply</span>(batting2122, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">ifelse</span>(<span class="fu">is.na</span>(x), <span class="dv">0</span>, x))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>batting2122 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(batting2122)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co">#check for NA values again</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">#sum(is.na(batting2122)) #clean of NA</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">#clean data by making the variables numeric besides Player and Team</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>exclude_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Player"</span>, <span class="st">"Team"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>batting2122 <span class="ot">&lt;-</span> batting2122 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span><span class="fu">one_of</span>(exclude_cols), <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(.))))</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co">#minimum AB 50</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="co">#AB 100 took out to much data</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>batting2122_clean <span class="ot">&lt;-</span> batting2122 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(AB <span class="sc">&gt;=</span> <span class="dv">50</span>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(batting2122_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Player              Team                 BA              OBP        
 Length:4369        Length:4369        Min.   :0.0600   Min.   :0.1160  
 Class :character   Class :character   1st Qu.:0.2380   1st Qu.:0.3110  
 Mode  :character   Mode  :character   Median :0.2770   Median :0.3550  
                                       Mean   :0.2795   Mean   :0.3568  
                                       3rd Qu.:0.3200   3rd Qu.:0.4010  
                                       Max.   :0.5220   Max.   :0.6460  
      SLG              OPS              GP              PA       
 Min.   :0.0730   Min.   :0.189   Min.   :16.00   Min.   : 56.0  
 1st Qu.:0.3300   1st Qu.:0.652   1st Qu.:40.00   1st Qu.:118.0  
 Median :0.4090   Median :0.765   Median :46.00   Median :143.0  
 Mean   :0.4282   Mean   :0.785   Mean   :44.83   Mean   :143.2  
 3rd Qu.:0.5100   3rd Qu.:0.904   3rd Qu.:51.00   3rd Qu.:169.0  
 Max.   :1.2120   Max.   :1.858   Max.   :70.00   Max.   :264.0  
       AB              R               H               X2B        
 Min.   : 50.0   Min.   : 1.00   Min.   :  3.00   Min.   : 0.000  
 1st Qu.:102.0   1st Qu.:12.00   1st Qu.: 25.00   1st Qu.: 3.000  
 Median :124.0   Median :19.00   Median : 34.00   Median : 6.000  
 Mean   :124.1   Mean   :20.84   Mean   : 35.58   Mean   : 6.117  
 3rd Qu.:146.0   3rd Qu.:27.00   3rd Qu.: 44.00   3rd Qu.: 8.000  
 Max.   :226.0   Max.   :84.00   Max.   :100.00   Max.   :27.000  
      X3B                HR              RBI            HBP        
 Min.   : 0.0000   Min.   : 0.000   Min.   : 0.0   Min.   : 0.000  
 1st Qu.: 0.0000   1st Qu.: 1.000   1st Qu.:11.0   1st Qu.: 1.000  
 Median : 0.0000   Median : 2.000   Median :18.0   Median : 2.000  
 Mean   : 0.8597   Mean   : 3.846   Mean   :20.1   Mean   : 2.881  
 3rd Qu.: 1.0000   3rd Qu.: 6.000   3rd Qu.:27.0   3rd Qu.: 4.000  
 Max.   :10.0000   Max.   :34.000   Max.   :92.0   Max.   :30.000  
       BB              K               SB               CS         
 Min.   : 0.00   Min.   : 2.00   Min.   : 0.000   Min.   : 0.0000  
 1st Qu.: 8.00   1st Qu.:15.00   1st Qu.: 1.000   1st Qu.: 0.0000  
 Median :12.00   Median :20.00   Median : 3.000   Median : 0.0000  
 Mean   :13.04   Mean   :21.08   Mean   : 4.874   Mean   : 0.9615  
 3rd Qu.:17.00   3rd Qu.:27.00   3rd Qu.: 7.000   3rd Qu.: 1.0000  
 Max.   :57.00   Max.   :56.00   Max.   :59.000   Max.   :10.0000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#want to see how many different teams are represented in my new dataset</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>team <span class="ot">&lt;-</span> <span class="fu">unique</span>(batting2122_clean<span class="sc">$</span>Team)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>num_teams <span class="ot">&lt;-</span> <span class="fu">length</span>(team)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(num_teams)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 302</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#want to see how many differnet players are represented in my new dataset</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>player <span class="ot">&lt;-</span> <span class="fu">unique</span>(batting2122_clean<span class="sc">$</span>Player)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>num_player <span class="ot">&lt;-</span> <span class="fu">length</span>(player)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(num_player)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3241</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#specific statistics</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">#batting average statistics</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(batting2122_clean<span class="sc">$</span>BA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2795322</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(batting2122_clean<span class="sc">$</span>BA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.277</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#hit statistics</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(batting2122_clean<span class="sc">$</span>H)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35.57885</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(batting2122_clean<span class="sc">$</span>H)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#at bat statistics</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(batting2122_clean<span class="sc">$</span>AB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 124.1479</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(batting2122_clean<span class="sc">$</span>AB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 124</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#note median is robust to outliers while mean can be influenced by outliers</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co">#since BA is calculate by H/AB lets look at their plots</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co">#create some scatter plots</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">#plot for hits</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(batting2122_clean, <span class="fu">aes</span>(<span class="at">x=</span>H, <span class="at">y=</span>BA)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot for at bats</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(batting2122_clean, <span class="fu">aes</span>(<span class="at">x=</span>AB, <span class="at">y=</span>BA)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Step 3:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create maximum model</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co">#checking for polynomial terms</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> Player, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> Team, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> OBP, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> SLG, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> OPS, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> GP, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> PA, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> AB, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> R, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-9.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> H, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-10.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> X2B, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-11.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> X3B, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-12.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> HR, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-13.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> RBI, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-14.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> HBP, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-15.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> BB, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-16.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> K, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-17.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> SB, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-18.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> CS, <span class="at">y =</span> BA), <span class="at">data =</span> batting2122_clean) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-2-19.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#checking for interaction terms</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co">#exclude Player and Team because they are categorical variables</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>batting2122_clean_numeric <span class="ot">&lt;-</span> batting2122_clean <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>Player, <span class="sc">-</span>Team)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate correlation matrix</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(batting2122_clean_numeric)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>cor_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             BA        OBP        SLG         OPS        GP        PA        AB
BA   1.00000000  0.8520561 0.76838671  0.84273228 0.2657848 0.4772484 0.4701777
OBP  0.85205609  1.0000000 0.75279376  0.88263992 0.2818851 0.4804173 0.3607832
SLG  0.76838671  0.7527938 1.00000000  0.97385457 0.3093555 0.4728650 0.4259699
OPS  0.84273228  0.8826399 0.97385457  1.00000000 0.3181818 0.5034554 0.4286847
GP   0.26578475  0.2818851 0.30935554  0.31818180 1.0000000 0.8841377 0.8632457
PA   0.47724838  0.4804173 0.47286502  0.50345537 0.8841377 1.0000000 0.9710293
AB   0.47017773  0.3607832 0.42596992  0.42868468 0.8632457 0.9710293 1.0000000
R    0.65000589  0.6465091 0.63106847  0.67376660 0.5967403 0.7594659 0.7150140
H    0.82311283  0.6774976 0.67431364  0.71531821 0.6750638 0.8582999 0.8723605
X2B  0.51101765  0.4665294 0.61976939  0.60357202 0.4449794 0.5745566 0.5623941
X3B  0.28949254  0.2108386 0.23092174  0.23769417 0.1925535 0.2767133 0.2973945
HR   0.39699136  0.4589486 0.83905548  0.75750855 0.3933664 0.4731231 0.4172632
RBI  0.54025860  0.5495078 0.81012789  0.76806993 0.5470394 0.6471324 0.6018927
HBP  0.07389271  0.3316173 0.17914810  0.24243101 0.2278464 0.2615190 0.1379105
BB   0.31353351  0.6637024 0.45430732  0.55342060 0.4810220 0.5845481 0.4046621
K   -0.21770800 -0.1009434 0.02142951 -0.01952195 0.3611653 0.2680198 0.2446496
SB   0.32741324  0.2654796 0.07363328  0.14424273 0.2308334 0.3317780 0.3383450
CS   0.23704783  0.1791956 0.02294343  0.07826237 0.1719458 0.2395761 0.2505973
             R          H        X2B         X3B           HR          RBI
BA  0.65000589 0.82311283 0.51101765 0.289492542  0.396991359  0.540258597
OBP 0.64650914 0.67749760 0.46652944 0.210838634  0.458948635  0.549507806
SLG 0.63106847 0.67431364 0.61976939 0.230921742  0.839055476  0.810127886
OPS 0.67376660 0.71531821 0.60357202 0.237694170  0.757508548  0.768069932
GP  0.59674026 0.67506385 0.44497945 0.192553514  0.393366355  0.547039361
PA  0.75946588 0.85829989 0.57455657 0.276713286  0.473123127  0.647132409
AB  0.71501397 0.87236054 0.56239407 0.297394471  0.417263196  0.601892666
R   1.00000000 0.81622678 0.51132070 0.377216460  0.523916495  0.599901275
H   0.81622678 1.00000000 0.62753284 0.350047992  0.482832979  0.667623803
X2B 0.51132070 0.62753284 1.00000000 0.149335576  0.429974433  0.619439989
X3B 0.37721646 0.35004799 0.14933558 1.000000000  0.001716688  0.126536163
HR  0.52391649 0.48283298 0.42997443 0.001716688  1.000000000  0.834568267
RBI 0.59990127 0.66762380 0.61943999 0.126536163  0.834568267  1.000000000
HBP 0.23821819 0.12269085 0.15700052 0.022934274  0.206126844  0.218356184
BB  0.53762504 0.42237762 0.35740365 0.076970832  0.472689419  0.500568938
K   0.09567634 0.02386167 0.04745861 0.015754922  0.222155819  0.154176514
SB  0.50748314 0.40533850 0.05241567 0.368926878 -0.082722671 -0.005113978
CS  0.33303030 0.29656260 0.02898046 0.270724591 -0.098341967 -0.047451086
             HBP         BB            K           SB            CS
BA  0.0738927076 0.31353351 -0.217708003  0.327413244  0.2370478315
OBP 0.3316173340 0.66370240 -0.100943356  0.265479585  0.1791955781
SLG 0.1791481045 0.45430732  0.021429510  0.073633282  0.0229434260
OPS 0.2424310077 0.55342060 -0.019521948  0.144242729  0.0782623716
GP  0.2278463733 0.48102196  0.361165333  0.230833369  0.1719458356
PA  0.2615190168 0.58454806  0.268019773  0.331777963  0.2395760832
AB  0.1379104506 0.40466206  0.244649640  0.338345004  0.2505972726
R   0.2382181936 0.53762504  0.095676345  0.507483138  0.3330303027
H   0.1226908523 0.42237762  0.023861670  0.405338496  0.2965625982
X2B 0.1570005168 0.35740365  0.047458615  0.052415675  0.0289804555
X3B 0.0229342745 0.07697083  0.015754922  0.368926878  0.2707245915
HR  0.2061268443 0.47268942  0.222155819 -0.082722671 -0.0983419672
RBI 0.2183561839 0.50056894  0.154176514 -0.005113978 -0.0474510857
HBP 1.0000000000 0.22177708  0.071984660  0.028693126  0.0001616812
BB  0.2217770790 1.00000000  0.240339901  0.143134398  0.0818414696
K   0.0719846598 0.24033990  1.000000000  0.001930951  0.0102017958
SB  0.0286931258 0.14313440  0.001930951  1.000000000  0.5824462921
CS  0.0001616812 0.08184147  0.010201796  0.582446292  1.0000000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convert to a data frame and filter</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>cor_dataframe <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">as.table</span>(cor_matrix))</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>strong_correlations <span class="ot">&lt;-</span> cor_dataframe <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(Freq)<span class="sc">&gt;</span><span class="fl">0.9</span> <span class="sc">&amp;</span> Freq <span class="sc">!=</span> <span class="dv">1</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>strong_correlations</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Var2      Freq
1  OPS  SLG 0.9738546
2  SLG  OPS 0.9738546
3   AB   PA 0.9710293
4   PA   AB 0.9710293</code></pre>
</div>
</div>
<p>Player and Team are categorical variables, so I will not add a polynomial term. The plots for OBP, SLG, OPS, R, and H are linear, so I will not add a polynomial term. Due to the size of my dataset and the large number of polynomial and interaction terms, I will not add polynomial terms for RBI, HBP, BB, SB, and CS because they do not have a solid correlation to BA. I am adding polynomial terms for GP, PA, AB, X2B, X3B, HR, and K because their plots are not linear. I used the correlation matrix to decide which interaction terms to add. I will add interaction terms for OPS:SLG and PA:AB because they have the highest correlation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#maximum model with specific interaction terms and polynomial terms</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>mod_max <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ OPS:SLG + PA:AB + I(GP^2) + I(PA^2) + I(AB^2) + 
    I(X2B^2) + I(X3B^2) + I(HR^2) + I(K^2), data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.145854 -0.017571 -0.002118  0.015997  0.192387 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.610e-01  1.684e-03  95.635   &lt;2e-16 ***
I(GP^2)     -1.305e-05  1.214e-06 -10.752   &lt;2e-16 ***
I(PA^2)      7.845e-07  3.263e-06   0.240   0.8100    
I(AB^2)      8.575e-06  4.556e-06   1.882   0.0599 .  
I(X2B^2)    -1.641e-04  9.009e-06 -18.216   &lt;2e-16 ***
I(X3B^2)    -6.505e-04  7.576e-05  -8.587   &lt;2e-16 ***
I(HR^2)     -4.595e-04  9.395e-06 -48.913   &lt;2e-16 ***
I(K^2)      -2.303e-05  1.018e-06 -22.620   &lt;2e-16 ***
OPS:SLG      3.378e-01  3.785e-03  89.229   &lt;2e-16 ***
PA:AB       -5.133e-06  7.719e-06  -0.665   0.5061    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02678 on 4359 degrees of freedom
Multiple R-squared:  0.8095,    Adjusted R-squared:  0.8091 
F-statistic:  2059 on 9 and 4359 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#backward selection with Mallow's Cp</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>var_sel <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(BA <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean, <span class="at">method =</span> <span class="st">"backward"</span>, <span class="at">nvmax =</span> <span class="dv">100</span>, <span class="at">really.big=</span><span class="cn">TRUE</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co">#minimizes the Mallow's Cp</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">summary</span>(var_sel)<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#write the final regression model</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(var_sel,<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       I(GP^2)       I(AB^2)      I(X2B^2)      I(X3B^2) 
 1.610413e-01 -1.305314e-05  7.485373e-06 -1.642481e-04 -6.503052e-04 
      I(HR^2)        I(K^2)       OPS:SLG         PA:AB 
-4.595905e-04 -2.304148e-05  3.378197e-01 -3.280247e-06 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create mod_best using regression model</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>mod_best <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB, batting2122_clean)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co">#homoscedasticity</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="co">#residual plot</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#BP test</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(mod_best)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  mod_best
BP = 587.39, df = 8, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#normality</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co">#QQ plot</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#KS test</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(<span class="fu">residuals</span>(mod_best), <span class="st">"pnorm"</span>, <span class="at">sd=</span><span class="fu">summary</span>(mod_best)<span class="sc">$</span>s)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  residuals(mod_best)
D = 0.034331, p-value = 6.734e-05
alternative hypothesis: two-sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate the AIC</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_best, <span class="at">k=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -19224.57</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get standard error value</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_best)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ I(GP^2) + I(AB^2) + I(X2B^2) + I(X3B^2) + I(HR^2) + 
    I(K^2) + OPS:SLG + PA:AB, data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.145923 -0.017561 -0.002061  0.015990  0.192285 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.610e-01  1.684e-03  95.647  &lt; 2e-16 ***
I(GP^2)     -1.305e-05  1.214e-06 -10.752  &lt; 2e-16 ***
I(AB^2)      7.485e-06  4.431e-07  16.893  &lt; 2e-16 ***
I(X2B^2)    -1.642e-04  8.992e-06 -18.266  &lt; 2e-16 ***
I(X3B^2)    -6.503e-04  7.575e-05  -8.585  &lt; 2e-16 ***
I(HR^2)     -4.596e-04  9.391e-06 -48.937  &lt; 2e-16 ***
I(K^2)      -2.304e-05  1.017e-06 -22.655  &lt; 2e-16 ***
OPS:SLG      3.378e-01  3.780e-03  89.359  &lt; 2e-16 ***
PA:AB       -3.280e-06  4.248e-07  -7.722 1.41e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02677 on 4360 degrees of freedom
Multiple R-squared:  0.8095,    Adjusted R-squared:  0.8092 
F-statistic:  2316 on 8 and 4360 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The estimated standard error for “best” model is <span class="math inline">\(0.02677\)</span>.</p>
<p>To check the goodness of fit, we will check the assumptions of normality and homoscedasticity. From the residual plot for homoscedasticity, the residuals appear to be somewhat randomly scattered and somewhat evenly spread across the fitted values. Also, the <span class="math inline">\(p-value = &lt;2.2*10^{-16} &lt; \alpha = 0.05\)</span>, so the assumption of homoscedasticity is violated. From the QQ plot for normality distributed residuals, the points fall close to the 45-degree line with a slight deviation at the right end. Also, the <span class="math inline">\(p-value = 6.734*10^{-05} &lt; \alpha = 0.05\)</span>, so the assumption of normality is violated. Therefore, the assumption of homoscedasticity and normality are violated.</p>
<p>The AIC of the “best” model is <span class="math inline">\(-19224.57\)</span>.</p>
<p>Since there were violations to both homoscedasticity and normality, suggest I need to do something else with my data before continuing. Since the QQ plot deviates up on the right side i will do a log transformation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#log transformation of the max model</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>mod_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(BA) <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(BA) ~ OPS:SLG + PA:AB + I(GP^2) + I(PA^2) + 
    I(AB^2) + I(X2B^2) + I(X3B^2) + I(HR^2) + I(K^2), data = batting2122_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.07565 -0.06239 -0.00063  0.06765  0.74778 

Coefficients:
              Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept) -1.749e+00  7.077e-03 -247.172   &lt;2e-16 ***
I(GP^2)     -4.580e-05  5.103e-06   -8.977   &lt;2e-16 ***
I(PA^2)     -1.291e-05  1.371e-05   -0.941    0.347    
I(AB^2)      1.071e-05  1.915e-05    0.559    0.576    
I(X2B^2)    -6.831e-04  3.786e-05  -18.043   &lt;2e-16 ***
I(X3B^2)    -2.977e-03  3.184e-04   -9.352   &lt;2e-16 ***
I(HR^2)     -1.804e-03  3.948e-05  -45.698   &lt;2e-16 ***
I(K^2)      -8.401e-05  4.279e-06  -19.634   &lt;2e-16 ***
OPS:SLG      1.257e+00  1.591e-02   79.016   &lt;2e-16 ***
PA:AB        1.811e-05  3.244e-05    0.558    0.577    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1125 on 4359 degrees of freedom
Multiple R-squared:  0.7639,    Adjusted R-squared:  0.7634 
F-statistic:  1567 on 9 and 4359 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">#redo variable selection</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="co">#backward selection with Mallow's Cp</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>var_sel2 <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(<span class="fu">log</span>(BA)<span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean, <span class="at">method =</span> <span class="st">"backward"</span>, <span class="at">nvmax =</span> <span class="dv">100</span>, <span class="at">really.big=</span><span class="cn">TRUE</span>)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="co">#minimizes the Mallow's Cp</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">summary</span>(var_sel2)<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co">#write the final regression model</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(var_sel2,<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       I(GP^2)       I(PA^2)       I(AB^2)      I(X2B^2) 
-1.749181e+00 -4.575484e-05 -5.267328e-06  2.138166e-05 -6.818492e-04 
     I(X3B^2)       I(HR^2)        I(K^2)       OPS:SLG 
-2.979879e-03 -1.803761e-03 -8.389579e-05  1.256699e+00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create mod_best using regression model</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>mod_best2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> OPS<span class="sc">:</span>SLG, batting2122_clean)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="co">#homoscedasticity</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="co">#residual plot</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best2,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">#BP test</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(mod_best2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  mod_best2
BP = 591.72, df = 8, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#normality</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="co">#QQ plot</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best2,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#KS test</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(<span class="fu">residuals</span>(mod_best2), <span class="st">"pnorm"</span>, <span class="at">sd=</span><span class="fu">summary</span>(mod_best2)<span class="sc">$</span>s)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  residuals(mod_best2)
D = 0.034133, p-value = 7.582e-05
alternative hypothesis: two-sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate the AIC</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_best2, <span class="at">k=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -19194.18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get standard error value</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_best2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ I(GP^2) + I(PA^2) + I(AB^2) + I(X2B^2) + (X3B^2) + 
    I(HR^2) + I(K^2) + OPS:SLG, data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.145872 -0.017695 -0.002259  0.016132  0.191362 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.619e-01  1.682e-03  96.261  &lt; 2e-16 ***
I(GP^2)     -1.304e-05  1.219e-06 -10.697  &lt; 2e-16 ***
I(PA^2)     -1.346e-06  1.801e-07  -7.476 9.24e-14 ***
I(AB^2)      5.498e-06  2.118e-07  25.965  &lt; 2e-16 ***
I(X2B^2)    -1.632e-04  9.057e-06 -18.018  &lt; 2e-16 ***
X3B         -2.500e-03  3.802e-04  -6.576 5.40e-11 ***
I(HR^2)     -4.589e-04  9.602e-06 -47.788  &lt; 2e-16 ***
I(K^2)      -2.301e-05  1.021e-06 -22.537  &lt; 2e-16 ***
OPS:SLG      3.370e-01  3.852e-03  87.491  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02687 on 4360 degrees of freedom
Multiple R-squared:  0.8082,    Adjusted R-squared:  0.8079 
F-statistic:  2297 on 8 and 4360 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The estimated standard error for the “best” model is <span class="math inline">\(0.02687\)</span>.</p>
<p>To check the goodness of fit, we will check the assumptions of normality and homoscedasticity. From the residual plot for homoscedasticity, the residuals appear to be somewhat randomly scattered and somewhat evenly spread across the fitted values. Also, the <span class="math inline">\(p-value = &lt;2.2*10^{-16} &lt; \alpha = 0.05\)</span>, so the assumption of homoscedasticity is violated. From the QQ plot for normality distributed residuals, the points fall close to the 45-degree line with a slight deviation at the right end. Also, the <span class="math inline">\(p-value = 7.582*10^{-05} &lt; \alpha = 0.05\)</span>, so the assumption of normality is violated. Therefore, the assumption of homoscedasticity and normality are violated.</p>
<p>The AIC of the “best” model is <span class="math inline">\(-19194.18\)</span>.</p>
<p>Since there were violations to both homoscedasticity and normality, suggest I need to do something else with my data before continuing. Now, I will try a square root transformation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>mod_sqrt <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(BA) <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_sqrt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sqrt(BA) ~ OPS:SLG + PA:AB + I(GP^2) + I(PA^2) + 
    I(AB^2) + I(X2B^2) + I(X3B^2) + I(HR^2) + I(K^2), data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.168380 -0.016479 -0.001056  0.016495  0.188404 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.109e-01  1.682e-03 244.320   &lt;2e-16 ***
I(GP^2)     -1.221e-05  1.213e-06 -10.067   &lt;2e-16 ***
I(PA^2)     -1.319e-06  3.260e-06  -0.405    0.686    
I(AB^2)      5.442e-06  4.551e-06   1.196    0.232    
I(X2B^2)    -1.662e-04  8.999e-06 -18.473   &lt;2e-16 ***
I(X3B^2)    -6.938e-04  7.567e-05  -9.169   &lt;2e-16 ***
I(HR^2)     -4.522e-04  9.384e-06 -48.192   &lt;2e-16 ***
I(K^2)      -2.184e-05  1.017e-06 -21.478   &lt;2e-16 ***
OPS:SLG      3.235e-01  3.781e-03  85.550   &lt;2e-16 ***
PA:AB       -4.869e-08  7.710e-06  -0.006    0.995    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02675 on 4359 degrees of freedom
Multiple R-squared:  0.7938,    Adjusted R-squared:  0.7934 
F-statistic:  1865 on 9 and 4359 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#redo variable selection</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="co">#backward selection with Mallow's Cp</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>var_sel3 <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(<span class="fu">sqrt</span>(BA) <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean, <span class="at">method =</span> <span class="st">"backward"</span>, <span class="at">nvmax =</span> <span class="dv">100</span>, <span class="at">really.big=</span><span class="cn">TRUE</span>)</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a><span class="co">#minimizes the Mallow's Cp</span></span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">summary</span>(var_sel3)<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co">#write the final regression model</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(var_sel3,<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       I(GP^2)       I(PA^2)       I(AB^2)      I(X2B^2) 
 4.109493e-01 -1.220950e-05 -1.339398e-06  5.413369e-06 -1.662461e-04 
     I(X3B^2)       I(HR^2)        I(K^2)       OPS:SLG 
-6.937827e-04 -4.522489e-04 -2.184342e-05  3.234798e-01 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create mod_best using regression model</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>mod_best3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> OPS<span class="sc">:</span>SLG, batting2122_clean)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="co">#homoscedasticity</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a><span class="co">#residual plot</span></span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best3,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co">#BP test</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(mod_best3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  mod_best3
BP = 589.1, df = 8, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co">#normality</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="co">#QQ plot</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best3,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#KS test</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(<span class="fu">residuals</span>(mod_best3), <span class="st">"pnorm"</span>, <span class="at">sd=</span><span class="fu">summary</span>(mod_best3)<span class="sc">$</span>s)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  residuals(mod_best3)
D = 0.034741, p-value = 5.257e-05
alternative hypothesis: two-sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate the AIC</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_best3, <span class="at">k=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -19224.19</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get standard error value</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_best3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ I(GP^2) + I(PA^2) + I(AB^2) + I(X2B^2) + I(X3B^2) + 
    I(HR^2) + I(K^2) + OPS:SLG, data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.146013 -0.017550 -0.002115  0.015982  0.192111 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.611e-01  1.684e-03  95.649  &lt; 2e-16 ***
I(GP^2)     -1.307e-05  1.214e-06 -10.766  &lt; 2e-16 ***
I(PA^2)     -1.382e-06  1.796e-07  -7.697 1.71e-14 ***
I(AB^2)      5.549e-06  2.105e-07  26.357  &lt; 2e-16 ***
I(X2B^2)    -1.645e-04  8.992e-06 -18.292  &lt; 2e-16 ***
I(X3B^2)    -6.498e-04  7.575e-05  -8.579  &lt; 2e-16 ***
I(HR^2)     -4.597e-04  9.392e-06 -48.942  &lt; 2e-16 ***
I(K^2)      -2.306e-05  1.017e-06 -22.677  &lt; 2e-16 ***
OPS:SLG      3.379e-01  3.783e-03  89.309  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02678 on 4360 degrees of freedom
Multiple R-squared:  0.8095,    Adjusted R-squared:  0.8092 
F-statistic:  2316 on 8 and 4360 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The estimated standard error for the “best” model is <span class="math inline">\(0.02678\)</span>.</p>
<p>To check the goodness of fit, we will check the assumptions of normality and homoscedasticity. From the residual plot for homoscedasticity, the residuals appear to be somewhat randomly scattered and somewhat evenly spread across the fitted values. Also, the <span class="math inline">\(p-value = &lt;2.2*10^{-16} &lt; \alpha = 0.05\)</span>, so the assumption of homoscedasticity is violated. From the QQ plot for normality distributed residuals, the points fall close to the 45-degree line with a slight deviation at the right end. Also, the <span class="math inline">\(p-value = 5.257*10^{-05} &lt; \alpha = 0.05\)</span>, so the assumption of normality is violated. Therefore, the assumption of homoscedasticity and normality are violated.</p>
<p>The AIC of the “best” model is <span class="math inline">\(-19224.19\)</span>.</p>
<p>Since there were violations to both homoscedasticity and normality, suggest I need to do something else with my data before continuing. Now, I will try weighted least squares.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co">#weighted least squares</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'nlme'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    collapse</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>mod_wls <span class="ot">&lt;-</span> <span class="fu">gls</span>(BA<span class="sc">~</span>OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_wls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: BA ~ OPS:SLG + PA:AB + I(GP^2) + I(PA^2) + I(AB^2) + I(X2B^2) +      I(X3B^2) + I(HR^2) + I(K^2) 
  Data: batting2122_clean 
       AIC       BIC   logLik
  -19004.2 -18934.02 9513.101

Coefficients:
                 Value   Std.Error   t-value p-value
(Intercept)  0.1610446 0.001683944  95.63535  0.0000
I(GP^2)     -0.0000131 0.000001214 -10.75187  0.0000
I(PA^2)      0.0000008 0.000003263   0.24040  0.8100
I(AB^2)      0.0000086 0.000004556   1.88211  0.0599
I(X2B^2)    -0.0001641 0.000009009 -18.21626  0.0000
I(X3B^2)    -0.0006505 0.000075757  -8.58654  0.0000
I(HR^2)     -0.0004595 0.000009395 -48.91264  0.0000
I(K^2)      -0.0000230 0.000001018 -22.61980  0.0000
OPS:SLG      0.3377748 0.003785500  89.22860  0.0000
PA:AB       -0.0000051 0.000007719  -0.66497  0.5061

 Correlation: 
         (Intr) I(GP^2 I(PA^2 I(AB^2 I(X2B^ I(X3B^ I(HR^2 I(K^2) OPS:SL
I(GP^2)  -0.550                                                        
I(PA^2)   0.008 -0.006                                                 
I(AB^2)  -0.016  0.016  0.995                                          
I(X2B^2)  0.302  0.016  0.060  0.055                                   
I(X3B^2)  0.173  0.044 -0.010 -0.022  0.149                            
I(HR^2)   0.548 -0.100  0.023  0.020  0.290  0.260                     
I(K^2)   -0.165 -0.203  0.044  0.051  0.033 -0.024 -0.152              
OPS:SLG  -0.662  0.185 -0.049 -0.024 -0.467 -0.275 -0.744  0.144       
PA:AB     0.007 -0.017 -0.998 -0.999 -0.061  0.014 -0.022 -0.047  0.034

Standardized residuals:
        Min          Q1         Med          Q3         Max 
-5.44690334 -0.65619493 -0.07909324  0.59740344  7.18468733 

Residual standard error: 0.02677733 
Degrees of freedom: 4369 total; 4359 residual</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co">#redo variable selection</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="co">#backward selection with Mallow's Cp</span></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>var_sel4 <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(BA <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean, <span class="at">method =</span> <span class="st">"backward"</span>, <span class="at">nvmax =</span> <span class="dv">100</span>, <span class="at">really.big=</span><span class="cn">TRUE</span>)</span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a><span class="co">#minimizes the Mallow's Cp</span></span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">summary</span>(var_sel4)<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co">#write the final regression model</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(var_sel4,<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       I(GP^2)       I(AB^2)      I(X2B^2)      I(X3B^2) 
 1.610413e-01 -1.305314e-05  7.485373e-06 -1.642481e-04 -6.503052e-04 
      I(HR^2)        I(K^2)       OPS:SLG         PA:AB 
-4.595905e-04 -2.304148e-05  3.378197e-01 -3.280247e-06 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create mod_best using regression model</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>mod_best4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB, batting2122_clean)</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a><span class="co">#homoscedasticity</span></span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a><span class="co">#residual plot</span></span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best4,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co">#BP test</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(mod_best4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  mod_best4
BP = 587.39, df = 8, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co">#normality</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="co">#QQ plot</span></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best4,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co">#KS test</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(<span class="fu">residuals</span>(mod_best4), <span class="st">"pnorm"</span>, <span class="at">sd=</span><span class="fu">summary</span>(mod_best4)<span class="sc">$</span>s)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  residuals(mod_best4)
D = 0.034331, p-value = 6.734e-05
alternative hypothesis: two-sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate the AIC</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_best4, <span class="at">k=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -19224.57</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get standard error value</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_best4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ I(GP^2) + I(AB^2) + I(X2B^2) + I(X3B^2) + I(HR^2) + 
    I(K^2) + OPS:SLG + PA:AB, data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.145923 -0.017561 -0.002061  0.015990  0.192285 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.610e-01  1.684e-03  95.647  &lt; 2e-16 ***
I(GP^2)     -1.305e-05  1.214e-06 -10.752  &lt; 2e-16 ***
I(AB^2)      7.485e-06  4.431e-07  16.893  &lt; 2e-16 ***
I(X2B^2)    -1.642e-04  8.992e-06 -18.266  &lt; 2e-16 ***
I(X3B^2)    -6.503e-04  7.575e-05  -8.585  &lt; 2e-16 ***
I(HR^2)     -4.596e-04  9.391e-06 -48.937  &lt; 2e-16 ***
I(K^2)      -2.304e-05  1.017e-06 -22.655  &lt; 2e-16 ***
OPS:SLG      3.378e-01  3.780e-03  89.359  &lt; 2e-16 ***
PA:AB       -3.280e-06  4.248e-07  -7.722 1.41e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02677 on 4360 degrees of freedom
Multiple R-squared:  0.8095,    Adjusted R-squared:  0.8092 
F-statistic:  2316 on 8 and 4360 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The estimated standard error for the “best” model is <span class="math inline">\(0.02677\)</span>.</p>
<p>To check the goodness of fit, we will check the assumptions of normality and homoscedasticity. From the residual plot for homoscedasticity, the residuals appear to be somewhat randomly scattered and somewhat evenly spread across the fitted values. Also, the <span class="math inline">\(p-value = &lt;2.2*10^{-16} &lt; \alpha = 0.05\)</span>, so the assumption of homoscedasticity is violated. From the QQ plot for normality distributed residuals, the points fall close to the 45-degree line with a slight deviation at the right end. Also, the <span class="math inline">\(p-value = 6.734*10^{-05} &lt; \alpha = 0.05\)</span>, so the assumption of normality is violated. Therefore, the assumption of homoscedasticity and normality are violated.</p>
<p>The AIC of the “best” model is <span class="math inline">\(-19224.57\)</span>.</p>
<p>Since there were violations to both homoscedasticity and normality, suggest I need to do something else with my data before continuing. Now, I will try robust regression.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co">#robust regression</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>mod_robust <span class="ot">&lt;-</span> <span class="fu">rlm</span>(BA <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean)</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_robust)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call: rlm(formula = BA ~ OPS:SLG + PA:AB + I(GP^2) + I(PA^2) + I(AB^2) + 
    I(X2B^2) + I(X3B^2) + I(HR^2) + I(K^2), data = batting2122_clean)
Residuals:
      Min        1Q    Median        3Q       Max 
-0.159177 -0.016184 -0.001444  0.016363  0.276437 

Coefficients:
            Value    Std. Error t value 
(Intercept)   0.1544   0.0016    97.7015
I(GP^2)       0.0000   0.0000   -10.7502
I(PA^2)       0.0000   0.0000    -0.0597
I(AB^2)       0.0000   0.0000     1.7058
I(X2B^2)     -0.0002   0.0000   -20.1118
I(X3B^2)     -0.0008   0.0001   -10.7576
I(HR^2)      -0.0006   0.0000   -63.8550
I(K^2)        0.0000   0.0000   -21.6980
OPS:SLG       0.3586   0.0036   100.9660
PA:AB         0.0000   0.0000    -0.4065

Residual standard error: 0.02418 on 4359 degrees of freedom</code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="co">#redo variable selection</span></span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="co">#backward selection with Mallow's Cp</span></span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>var_sel5 <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(BA <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean, <span class="at">method =</span> <span class="st">"backward"</span>, <span class="at">nvmax =</span> <span class="dv">100</span>, <span class="at">really.big=</span><span class="cn">TRUE</span>)</span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a><span class="co">#minimizes the Mallow's Cp</span></span>
<span id="cb122-6"><a href="#cb122-6" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">summary</span>(var_sel5)<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co">#write the final regression model</span></span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(var_sel5,<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       I(GP^2)       I(AB^2)      I(X2B^2)      I(X3B^2) 
 1.610413e-01 -1.305314e-05  7.485373e-06 -1.642481e-04 -6.503052e-04 
      I(HR^2)        I(K^2)       OPS:SLG         PA:AB 
-4.595905e-04 -2.304148e-05  3.378197e-01 -3.280247e-06 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create mod_best using regression model</span></span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a>mod_best5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> PA<span class="sc">:</span>AB, batting2122_clean)</span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-4"><a href="#cb126-4" aria-hidden="true" tabindex="-1"></a><span class="co">#homoscedasticity</span></span>
<span id="cb126-5"><a href="#cb126-5" aria-hidden="true" tabindex="-1"></a><span class="co">#residual plot</span></span>
<span id="cb126-6"><a href="#cb126-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best5,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="co">#BP test</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(mod_best5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  mod_best5
BP = 587.39, df = 8, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co">#normality</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a><span class="co">#QQ plot</span></span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best5,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="co">#KS test</span></span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(<span class="fu">residuals</span>(mod_best5), <span class="st">"pnorm"</span>, <span class="at">sd=</span><span class="fu">summary</span>(mod_best5)<span class="sc">$</span>s)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  residuals(mod_best5)
D = 0.034331, p-value = 6.734e-05
alternative hypothesis: two-sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate the AIC</span></span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_best5, <span class="at">k=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -19224.57</code></pre>
</div>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get standard error value</span></span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_best5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ I(GP^2) + I(AB^2) + I(X2B^2) + I(X3B^2) + I(HR^2) + 
    I(K^2) + OPS:SLG + PA:AB, data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.145923 -0.017561 -0.002061  0.015990  0.192285 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.610e-01  1.684e-03  95.647  &lt; 2e-16 ***
I(GP^2)     -1.305e-05  1.214e-06 -10.752  &lt; 2e-16 ***
I(AB^2)      7.485e-06  4.431e-07  16.893  &lt; 2e-16 ***
I(X2B^2)    -1.642e-04  8.992e-06 -18.266  &lt; 2e-16 ***
I(X3B^2)    -6.503e-04  7.575e-05  -8.585  &lt; 2e-16 ***
I(HR^2)     -4.596e-04  9.391e-06 -48.937  &lt; 2e-16 ***
I(K^2)      -2.304e-05  1.017e-06 -22.655  &lt; 2e-16 ***
OPS:SLG      3.378e-01  3.780e-03  89.359  &lt; 2e-16 ***
PA:AB       -3.280e-06  4.248e-07  -7.722 1.41e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02677 on 4360 degrees of freedom
Multiple R-squared:  0.8095,    Adjusted R-squared:  0.8092 
F-statistic:  2316 on 8 and 4360 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The estimated standard error for the “best” model is <span class="math inline">\(0.02677\)</span>.</p>
<p>To check the goodness of fit, we will check the assumptions of normality and homoscedasticity. From the residual plot for homoscedasticity, the residuals appear to be somewhat randomly scattered and somewhat evenly spread across the fitted values. Also, the <span class="math inline">\(p-value = &lt;2.2*10^{-16} &lt; \alpha = 0.05\)</span>, so the assumption of homoscedasticity is violated. From the QQ plot for normality distributed residuals, the points fall close to the 45-degree line with a slight deviation at the right end. Also, the <span class="math inline">\(p-value = 6.734*10^{-05} &lt; \alpha = 0.05\)</span>, so the assumption of normality is violated. Therefore, the assumption of homoscedasticity and normality are violated.</p>
<p>The AIC of the “best” model is <span class="math inline">\(-19224.57\)</span>.</p>
<p>Checking the multicollinearity of my max model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co">#CHECK MULTICOLLINEARITY of max model</span></span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span> <span class="fu">vif</span>(mod_max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>vif_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     I(GP^2)      I(PA^2)      I(AB^2)     I(X2B^2)     I(X3B^2)      I(HR^2) 
    4.910802  6846.975551  7470.657431     1.864422     1.179455     2.901863 
      I(K^2)      OPS:SLG        PA:AB 
    1.180223     3.905511 28062.890999 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove PA:AB</span></span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>mod_max7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(PA<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean)</span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_max7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ OPS:SLG + I(GP^2) + I(PA^2) + I(AB^2) + I(X2B^2) + 
    I(X3B^2) + I(HR^2) + I(K^2), data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.146013 -0.017550 -0.002115  0.015982  0.192111 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.611e-01  1.684e-03  95.649  &lt; 2e-16 ***
I(GP^2)     -1.307e-05  1.214e-06 -10.766  &lt; 2e-16 ***
I(PA^2)     -1.382e-06  1.796e-07  -7.697 1.71e-14 ***
I(AB^2)      5.549e-06  2.105e-07  26.357  &lt; 2e-16 ***
I(X2B^2)    -1.645e-04  8.992e-06 -18.292  &lt; 2e-16 ***
I(X3B^2)    -6.498e-04  7.575e-05  -8.579  &lt; 2e-16 ***
I(HR^2)     -4.597e-04  9.392e-06 -48.942  &lt; 2e-16 ***
I(K^2)      -2.306e-05  1.017e-06 -22.677  &lt; 2e-16 ***
OPS:SLG      3.379e-01  3.783e-03  89.309  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02678 on 4360 degrees of freedom
Multiple R-squared:  0.8095,    Adjusted R-squared:  0.8092 
F-statistic:  2316 on 8 and 4360 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span> <span class="fu">vif</span>(mod_max7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a>vif_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  I(GP^2)   I(PA^2)   I(AB^2)  I(X2B^2)  I(X3B^2)   I(HR^2)    I(K^2)   OPS:SLG 
 4.909347 20.738098 15.951691  1.857493  1.179230  2.900479  1.177634  3.900937 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove I(PA^2)</span></span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a>mod_max8 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean)</span>
<span id="cb151-3"><a href="#cb151-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_max8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ OPS:SLG + I(GP^2) + I(AB^2) + I(X2B^2) + I(X3B^2) + 
    I(HR^2) + I(K^2), data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.138900 -0.017812 -0.002013  0.015884  0.193324 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.647e-01  1.626e-03 101.284   &lt;2e-16 ***
I(GP^2)     -1.702e-05  1.107e-06 -15.376   &lt;2e-16 ***
I(AB^2)      4.173e-06  1.120e-07  37.273   &lt;2e-16 ***
I(X2B^2)    -1.651e-04  9.051e-06 -18.239   &lt;2e-16 ***
I(X3B^2)    -6.131e-04  7.610e-05  -8.057    1e-15 ***
I(HR^2)     -4.578e-04  9.452e-06 -48.440   &lt;2e-16 ***
I(K^2)      -2.346e-05  1.022e-06 -22.948   &lt;2e-16 ***
OPS:SLG      3.298e-01  3.660e-03  90.105   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02695 on 4361 degrees of freedom
Multiple R-squared:  0.8069,    Adjusted R-squared:  0.8066 
F-statistic:  2604 on 7 and 4361 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span> <span class="fu">vif</span>(mod_max8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a>vif_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> I(GP^2)  I(AB^2) I(X2B^2) I(X3B^2)  I(HR^2)   I(K^2)  OPS:SLG 
4.029802 4.452005 1.857350 1.174566 2.898614 1.174553 3.604146 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="co">#AFTER DEALING WITH MULTI</span></span>
<span id="cb157-2"><a href="#cb157-2" aria-hidden="true" tabindex="-1"></a><span class="co">#backward selection with Mallow's Cp</span></span>
<span id="cb157-3"><a href="#cb157-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb157-4"><a href="#cb157-4" aria-hidden="true" tabindex="-1"></a>var_sel8 <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(BA <span class="sc">~</span> OPS<span class="sc">:</span>SLG <span class="sc">+</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>), batting2122_clean, <span class="at">method =</span> <span class="st">"backward"</span>, <span class="at">nvmax =</span> <span class="dv">100</span>, <span class="at">really.big=</span><span class="cn">TRUE</span>)</span>
<span id="cb157-5"><a href="#cb157-5" aria-hidden="true" tabindex="-1"></a><span class="co">#minimizes the Mallow's Cp</span></span>
<span id="cb157-6"><a href="#cb157-6" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">summary</span>(var_sel8)<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co">#write the final regression model</span></span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(var_sel8,<span class="dv">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       I(GP^2)       I(AB^2)      I(X2B^2)      I(X3B^2) 
 1.647079e-01 -1.702369e-05  4.173064e-06 -1.650899e-04 -6.131314e-04 
      I(HR^2)        I(K^2)       OPS:SLG 
-4.578416e-04 -2.346279e-05  3.298294e-01 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create mod_best using regression model</span></span>
<span id="cb161-2"><a href="#cb161-2" aria-hidden="true" tabindex="-1"></a>mod_best8 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> OPS<span class="sc">:</span>SLG, batting2122_clean)</span>
<span id="cb161-3"><a href="#cb161-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb161-4"><a href="#cb161-4" aria-hidden="true" tabindex="-1"></a><span class="co">#homoscedasticity</span></span>
<span id="cb161-5"><a href="#cb161-5" aria-hidden="true" tabindex="-1"></a><span class="co">#residual plot</span></span>
<span id="cb161-6"><a href="#cb161-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best8,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb162"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="co">#BP test</span></span>
<span id="cb162-2"><a href="#cb162-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb162-3"><a href="#cb162-3" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(mod_best8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  mod_best8
BP = 550.28, df = 7, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb164"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb164-1"><a href="#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="co">#normality</span></span>
<span id="cb164-2"><a href="#cb164-2" aria-hidden="true" tabindex="-1"></a><span class="co">#QQ plot</span></span>
<span id="cb164-3"><a href="#cb164-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_best8,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="co">#KS test</span></span>
<span id="cb165-2"><a href="#cb165-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(<span class="fu">residuals</span>(mod_best8), <span class="st">"pnorm"</span>, <span class="at">sd=</span><span class="fu">summary</span>(mod_best8)<span class="sc">$</span>s)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  residuals(mod_best8)
D = 0.035014, p-value = 4.452e-05
alternative hypothesis: two-sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb167"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb167-1"><a href="#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate the AIC</span></span>
<span id="cb167-2"><a href="#cb167-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_best8, <span class="at">k=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -19167.22</code></pre>
</div>
<div class="sourceCode cell-code" id="cb169"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb169-1"><a href="#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get standard error value</span></span>
<span id="cb169-2"><a href="#cb169-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_best8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ I(GP^2) + I(AB^2) + I(X2B^2) + I(X3B^2) + I(HR^2) + 
    I(K^2) + OPS:SLG, data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.138900 -0.017812 -0.002013  0.015884  0.193324 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.647e-01  1.626e-03 101.284   &lt;2e-16 ***
I(GP^2)     -1.702e-05  1.107e-06 -15.376   &lt;2e-16 ***
I(AB^2)      4.173e-06  1.120e-07  37.273   &lt;2e-16 ***
I(X2B^2)    -1.651e-04  9.051e-06 -18.239   &lt;2e-16 ***
I(X3B^2)    -6.131e-04  7.610e-05  -8.057    1e-15 ***
I(HR^2)     -4.578e-04  9.452e-06 -48.440   &lt;2e-16 ***
I(K^2)      -2.346e-05  1.022e-06 -22.948   &lt;2e-16 ***
OPS:SLG      3.298e-01  3.660e-03  90.105   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02695 on 4361 degrees of freedom
Multiple R-squared:  0.8069,    Adjusted R-squared:  0.8066 
F-statistic:  2604 on 7 and 4361 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The estimated standard error for the “best” model is <span class="math inline">\(0.02695\)</span>.</p>
<p>To check the goodness of fit, we will check the assumptions of normality and homoscedasticity. From the residual plot for homoscedasticity, the residuals appear to be somewhat randomly scattered and somewhat evenly spread across the fitted values. Also, the <span class="math inline">\(p-value = &lt;2.2*10^{-16} &lt; \alpha = 0.05\)</span>, so the assumption of homoscedasticity is violated. From the QQ plot for normality distributed residuals, the points fall close to the 45-degree line with a slight deviation at the right end. Also, the <span class="math inline">\(p-value = 4.452*10^{-05} &lt; \alpha = 0.05\)</span>, so the assumption of normality is violated. Therefore, the assumption of homoscedasticity and normality are violated.</p>
<p>The AIC of the “best” model is <span class="math inline">\(-19167.22\)</span>.</p>
<p>Notice all the AIC values are very close, which means they have a similar fits to the data. P-values are also very similar and assumptions are always violated. Tried all the transformations and now them seemed to be a good fit for the data due to the violations. There could be a model that works, but we have not succeeded one of those in this class. Due to this, I will use the “best” model that was checked to multicollinearity and will continue the analysis using that model.</p>
<p>beta regression technique- look into</p>
<p>stating that we could look into in the future</p>
<p>tried all the transformations and didnt-not good fit for this data because of the violations</p>
<p>could be a model that works but we are not discussing them in this class</p>
<p>include this stuff in the paper</p>
<p>Step 4:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb171"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb171-1"><a href="#cb171-1" aria-hidden="true" tabindex="-1"></a><span class="co">#using mod_best8 which is the max model with the multicollinearity checked</span></span>
<span id="cb171-2"><a href="#cb171-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb171-3"><a href="#cb171-3" aria-hidden="true" tabindex="-1"></a><span class="co">#present the results of the linear regression model</span></span>
<span id="cb171-4"><a href="#cb171-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(var_sel8,<span class="dv">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       I(GP^2)       I(AB^2)      I(X2B^2)      I(X3B^2) 
 1.647079e-01 -1.702369e-05  4.173064e-06 -1.650899e-04 -6.131314e-04 
      I(HR^2)        I(K^2)       OPS:SLG 
-4.578416e-04 -2.346279e-05  3.298294e-01 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb173"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb173-1"><a href="#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create mod_best using regression model</span></span>
<span id="cb173-2"><a href="#cb173-2" aria-hidden="true" tabindex="-1"></a>mod_best8 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BA <span class="sc">~</span> <span class="fu">I</span>(GP<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(AB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X2B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X3B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(HR<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(K<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> OPS<span class="sc">:</span>SLG, batting2122_clean)</span>
<span id="cb173-3"><a href="#cb173-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb173-4"><a href="#cb173-4" aria-hidden="true" tabindex="-1"></a><span class="co">#interpret the coefficients of the model, including their signifiance and direction</span></span>
<span id="cb173-5"><a href="#cb173-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod_best8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)       I(GP^2)       I(AB^2)      I(X2B^2)      I(X3B^2) 
 1.647079e-01 -1.702369e-05  4.173064e-06 -1.650899e-04 -6.131314e-04 
      I(HR^2)        I(K^2)       OPS:SLG 
-4.578416e-04 -2.346279e-05  3.298294e-01 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb175"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb175-1"><a href="#cb175-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_best8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BA ~ I(GP^2) + I(AB^2) + I(X2B^2) + I(X3B^2) + I(HR^2) + 
    I(K^2) + OPS:SLG, data = batting2122_clean)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.138900 -0.017812 -0.002013  0.015884  0.193324 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.647e-01  1.626e-03 101.284   &lt;2e-16 ***
I(GP^2)     -1.702e-05  1.107e-06 -15.376   &lt;2e-16 ***
I(AB^2)      4.173e-06  1.120e-07  37.273   &lt;2e-16 ***
I(X2B^2)    -1.651e-04  9.051e-06 -18.239   &lt;2e-16 ***
I(X3B^2)    -6.131e-04  7.610e-05  -8.057    1e-15 ***
I(HR^2)     -4.578e-04  9.452e-06 -48.440   &lt;2e-16 ***
I(K^2)      -2.346e-05  1.022e-06 -22.948   &lt;2e-16 ***
OPS:SLG      3.298e-01  3.660e-03  90.105   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02695 on 4361 degrees of freedom
Multiple R-squared:  0.8069,    Adjusted R-squared:  0.8066 
F-statistic:  2604 on 7 and 4361 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb177"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb177-1"><a href="#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I(GP^2) = -1.702369*10^{-05}</span></span>
<span id="cb177-2"><a href="#cb177-2" aria-hidden="true" tabindex="-1"></a><span class="co">#For every 1 unit increase in GP, the predicted batting average will decrease by -1.702369*10^{-05}, holding all other variables constant. Notice the p-value is 2*10^-16 indicates the coefficient is statistically signficant. </span></span>
<span id="cb177-3"><a href="#cb177-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb177-4"><a href="#cb177-4" aria-hidden="true" tabindex="-1"></a><span class="co">#I(AB^2) = 4.173*10^{-06}</span></span>
<span id="cb177-5"><a href="#cb177-5" aria-hidden="true" tabindex="-1"></a><span class="co">#For every 1 unit increase in AB, the predicted batting average will increase by 4.173*10^{-06}, holding all other variables constant. Notice the p-value is 2*10^-16 indicates the coefficient is statistically signficant.</span></span>
<span id="cb177-6"><a href="#cb177-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb177-7"><a href="#cb177-7" aria-hidden="true" tabindex="-1"></a><span class="co">#I(X2B^2) = -1.651*10^{-04}</span></span>
<span id="cb177-8"><a href="#cb177-8" aria-hidden="true" tabindex="-1"></a><span class="co">#For every 1 unit increase in X2B, the predicted batting average will decrease by -1.651*10^{-04}, holding all other variables constant. Notice the p-value is 2*10^-16 indicates the coefficient is statistically signficant.</span></span>
<span id="cb177-9"><a href="#cb177-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb177-10"><a href="#cb177-10" aria-hidden="true" tabindex="-1"></a><span class="co">#I(X3B^2) = -6.131*10^{-04}</span></span>
<span id="cb177-11"><a href="#cb177-11" aria-hidden="true" tabindex="-1"></a><span class="co">#For every 1 unit increase in X3B,the predicted batting average will decrease by -6.131*10^{-04}, holding all other variables constant. Notice the p-value is 1*10^-15 indicates the coefficient is statistically signficant.</span></span>
<span id="cb177-12"><a href="#cb177-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb177-13"><a href="#cb177-13" aria-hidden="true" tabindex="-1"></a><span class="co">#I(HR^2) = -4.578416*10^{-04}</span></span>
<span id="cb177-14"><a href="#cb177-14" aria-hidden="true" tabindex="-1"></a><span class="co">#For every 1 unit increase in HR,the predicted batting average will decrease by -4.578416*10^{-04}, holding all other variables constant. Notice the p-value is 2*10^-16 indicates the coefficient is statistically signficant.</span></span>
<span id="cb177-15"><a href="#cb177-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb177-16"><a href="#cb177-16" aria-hidden="true" tabindex="-1"></a><span class="co">#I(K^2) = -2.346279*10^{-05}</span></span>
<span id="cb177-17"><a href="#cb177-17" aria-hidden="true" tabindex="-1"></a><span class="co">#For every 1 unit increase in K,the predicted batting average will decrease by -2.346279*10^{-05}, holding all other variables constant. Notice the p-value is 2*10^-16 indicates the coefficient is statistically signficant.</span></span>
<span id="cb177-18"><a href="#cb177-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb177-19"><a href="#cb177-19" aria-hidden="true" tabindex="-1"></a><span class="co">#OPS:SLG = 0.3298</span></span>
<span id="cb177-20"><a href="#cb177-20" aria-hidden="true" tabindex="-1"></a><span class="co">#For every 1 unit increase in OPS:SLG,the predicted batting average will increase by 0.3298 holding all other variables constant. Notice the p-value is 2*10^-16 indicates the coefficient is statistically signficant.</span></span>
<span id="cb177-21"><a href="#cb177-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb177-22"><a href="#cb177-22" aria-hidden="true" tabindex="-1"></a><span class="co">#discuss overall fit of the model and its predictive power</span></span>
<span id="cb177-23"><a href="#cb177-23" aria-hidden="true" tabindex="-1"></a><span class="co">#lets look at the r^2 value</span></span>
<span id="cb177-24"><a href="#cb177-24" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod_best8)<span class="sc">$</span>r.squared</span>
<span id="cb177-25"><a href="#cb177-25" aria-hidden="true" tabindex="-1"></a>r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8069272</code></pre>
</div>
<div class="sourceCode cell-code" id="cb179"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb179-1"><a href="#cb179-1" aria-hidden="true" tabindex="-1"></a><span class="co">#80.7% of the variabililty in batting average can be explained through a linear relationship with I(GP^2), I(AB^2), I(X2B^2), I(X3B^2), I(HR^2), I(K^2), and OPS:SLG.</span></span>
<span id="cb179-2"><a href="#cb179-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb179-3"><a href="#cb179-3" aria-hidden="true" tabindex="-1"></a><span class="co">#High r2 suggest the model provides a good fit for the data, so it would be reliable for making predictions.</span></span>
<span id="cb179-4"><a href="#cb179-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb179-5"><a href="#cb179-5" aria-hidden="true" tabindex="-1"></a><span class="co">#predictions</span></span>
<span id="cb179-6"><a href="#cb179-6" aria-hidden="true" tabindex="-1"></a><span class="co">#create new dataframe with values</span></span>
<span id="cb179-7"><a href="#cb179-7" aria-hidden="true" tabindex="-1"></a>new_data8 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb179-8"><a href="#cb179-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">GP =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">55</span>, <span class="dv">60</span>, <span class="dv">65</span>),</span>
<span id="cb179-9"><a href="#cb179-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">AB =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">150</span>, <span class="dv">170</span>, <span class="dv">200</span>, <span class="dv">225</span>),</span>
<span id="cb179-10"><a href="#cb179-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">X2B =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">27</span>),</span>
<span id="cb179-11"><a href="#cb179-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">X3B =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>, <span class="dv">10</span>),</span>
<span id="cb179-12"><a href="#cb179-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">HR =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">30</span>),</span>
<span id="cb179-13"><a href="#cb179-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">K =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">30</span>, <span class="dv">35</span>),</span>
<span id="cb179-14"><a href="#cb179-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">OPS =</span> <span class="fu">c</span>(<span class="fl">0.450</span>, <span class="fl">0.500</span>, <span class="fl">0.550</span>, <span class="fl">0.600</span>, <span class="fl">0.640</span>),</span>
<span id="cb179-15"><a href="#cb179-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">SLG =</span> <span class="fu">c</span>(<span class="fl">0.500</span>, <span class="fl">0.600</span>, <span class="fl">0.700</span>, <span class="fl">0.800</span>, <span class="fl">0.900</span>)</span>
<span id="cb179-16"><a href="#cb179-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb179-17"><a href="#cb179-17" aria-hidden="true" tabindex="-1"></a>predictbest8 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_best8, new_data8)</span>
<span id="cb179-18"><a href="#cb179-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb179-19"><a href="#cb179-19" aria-hidden="true" tabindex="-1"></a><span class="co">#plot HR vs predicted BA </span></span>
<span id="cb179-20"><a href="#cb179-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb179-21"><a href="#cb179-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>new_data8<span class="sc">$</span>HR, <span class="at">y =</span> predictbest8), <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>new_data8<span class="sc">$</span>HR, <span class="at">y =</span> predictbest8), <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Home Runs vs Predicted Batting Average"</span>, <span class="at">x =</span> <span class="st">"Home Runs"</span>, <span class="at">y =</span> <span class="st">"Predicted Batting Average"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb180"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb180-1"><a href="#cb180-1" aria-hidden="true" tabindex="-1"></a><span class="co">#provide insight based on the regression results</span></span>
<span id="cb180-2"><a href="#cb180-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb180-3"><a href="#cb180-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Increase in GP slightly decreasing batting average makes sense.</span></span>
<span id="cb180-4"><a href="#cb180-4" aria-hidden="true" tabindex="-1"></a><span class="co">#More AB leading to higher batting average also makes sense.</span></span>
<span id="cb180-5"><a href="#cb180-5" aria-hidden="true" tabindex="-1"></a><span class="co">#X2B and X3B, suggest focusing on other factors to increase BA then trying to hit doubles and triples (this would increase SLG).</span></span>
<span id="cb180-6"><a href="#cb180-6" aria-hidden="true" tabindex="-1"></a><span class="co">#HR this negative affect suggest you should reduce HR, but those are helpful.</span></span>
<span id="cb180-7"><a href="#cb180-7" aria-hidden="true" tabindex="-1"></a><span class="co">#K this negative affect suggest reducing K's to help increase BA, makes sense.</span></span>
<span id="cb180-8"><a href="#cb180-8" aria-hidden="true" tabindex="-1"></a><span class="co">#OPS:SLG positive interaction that good OPS and SLG can boost batting average, makes sense. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Step 5:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb181"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb181-1"><a href="#cb181-1" aria-hidden="true" tabindex="-1"></a><span class="co">#evalute the strengths and weakness of the linear regression analysis</span></span>
<span id="cb181-2"><a href="#cb181-2" aria-hidden="true" tabindex="-1"></a><span class="co">#will discuss in paper</span></span>
<span id="cb181-3"><a href="#cb181-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb181-4"><a href="#cb181-4" aria-hidden="true" tabindex="-1"></a><span class="co">#discuss limitations of the study, data constraints or model assumptions</span></span>
<span id="cb181-5"><a href="#cb181-5" aria-hidden="true" tabindex="-1"></a><span class="co">#will discuss in paper</span></span>
<span id="cb181-6"><a href="#cb181-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb181-7"><a href="#cb181-7" aria-hidden="true" tabindex="-1"></a><span class="co">#consider alternative approaches or models that could improve the analysis</span></span>
<span id="cb181-8"><a href="#cb181-8" aria-hidden="true" tabindex="-1"></a><span class="co">#LASSO</span></span>
<span id="cb181-9"><a href="#cb181-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loaded glmnet 4.1-8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb186"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb186-1"><a href="#cb186-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(BA <span class="sc">~</span> OBP <span class="sc">+</span> SLG <span class="sc">+</span> OPS <span class="sc">+</span> GP <span class="sc">+</span> PA <span class="sc">+</span> AB <span class="sc">+</span> R <span class="sc">+</span> H <span class="sc">+</span> X2B <span class="sc">+</span> X3B <span class="sc">+</span> HR <span class="sc">+</span> RBI <span class="sc">+</span> HBP <span class="sc">+</span> BB <span class="sc">+</span> K <span class="sc">+</span> SB <span class="sc">+</span> CS, batting2122_clean)</span>
<span id="cb186-2"><a href="#cb186-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> batting2122_clean<span class="sc">$</span>BA</span>
<span id="cb186-3"><a href="#cb186-3" aria-hidden="true" tabindex="-1"></a>mod_lasso <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x,y,<span class="at">alpha=</span><span class="dv">1</span>)</span>
<span id="cb186-4"><a href="#cb186-4" aria-hidden="true" tabindex="-1"></a>best_lambda <span class="ot">&lt;-</span> mod_lasso<span class="sc">$</span>lambda.min</span>
<span id="cb186-5"><a href="#cb186-5" aria-hidden="true" tabindex="-1"></a>best_lambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.869978e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb188"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb188-1"><a href="#cb188-1" aria-hidden="true" tabindex="-1"></a>coefs_lasso <span class="ot">&lt;-</span> <span class="fu">coef</span>(mod_lasso, <span class="at">s=</span> best_lambda)</span>
<span id="cb188-2"><a href="#cb188-2" aria-hidden="true" tabindex="-1"></a>coefs_lasso</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>19 x 1 sparse Matrix of class "dgCMatrix"
                       s1
(Intercept)  3.539369e-02
(Intercept)  .           
OBP          2.561164e-01
SLG          1.147739e-02
OPS          1.913519e-01
GP          -7.902201e-05
PA           .           
AB          -3.595859e-04
R            .           
H            2.896432e-03
X2B         -1.431087e-03
X3B         -3.242461e-03
HR          -4.317083e-03
RBI          1.218889e-04
HBP         -1.878159e-03
BB          -1.823557e-03
K           -1.059839e-04
SB          -2.178902e-05
CS           .           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb190"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb190-1"><a href="#cb190-1" aria-hidden="true" tabindex="-1"></a><span class="co">#from LASSO, PA, R, and CS are zero</span></span>
<span id="cb190-2"><a href="#cb190-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb190-3"><a href="#cb190-3" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_lasso, <span class="at">newx=</span>x, <span class="at">s =</span> best_lambda)</span>
<span id="cb190-4"><a href="#cb190-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb190-5"><a href="#cb190-5" aria-hidden="true" tabindex="-1"></a><span class="co">#create dataframe with actual and predicted value</span></span>
<span id="cb190-6"><a href="#cb190-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb190-7"><a href="#cb190-7" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Actual =</span> y, <span class="at">Predicted =</span> <span class="fu">as.vector</span>(predictions))</span>
<span id="cb190-8"><a href="#cb190-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb190-9"><a href="#cb190-9" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb190-10"><a href="#cb190-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(results, <span class="fu">aes</span>(<span class="at">x=</span>Actual, <span class="at">y =</span> Predicted)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span> <span class="st">"Actual vs Predicted Batting Averages"</span>, <span class="at">x =</span> <span class="st">"Actual Batting Averages"</span>, <span class="at">y =</span> <span class="st">"predicted Batting Average"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stat408project_Houghton_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb191"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb191-1"><a href="#cb191-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The blue points(predicted values) fall very close to the red line (actual line), which indiactes that the LASSO model is good at predicting batting average. </span></span>
<span id="cb191-2"><a href="#cb191-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb191-3"><a href="#cb191-3" aria-hidden="true" tabindex="-1"></a><span class="co">#reflects on the implications of the findings and their relevance to the broader field</span></span>
<span id="cb191-4"><a href="#cb191-4" aria-hidden="true" tabindex="-1"></a><span class="co">#will discuss in paper</span></span>
<span id="cb191-5"><a href="#cb191-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb191-6"><a href="#cb191-6" aria-hidden="true" tabindex="-1"></a><span class="co">#describe what you would have done if you had more time (future work)</span></span>
<span id="cb191-7"><a href="#cb191-7" aria-hidden="true" tabindex="-1"></a><span class="co">#will discuss in paper</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>